services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      ecp_req_network:
        ipv4_address: 192.168.129.2
    ports:
      - "9001:9000"  # Host:Container

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "4902:80"
      - "4904:443"  # เพิ่มการเปิด port 443 สำหรับ HTTPS
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certificates.crt:/etc/ssl/certs/certificate.crt  # ใบรับรอง SSL
      - ./ssl/certificates.key:/etc/ssl/private/private.key  # คีย์ส่วนตัว SSL
    networks:
      ecp_req_network:
        ipv4_address: 192.168.129.3
    depends_on:
      - app
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: adminppl
      MYSQL_DATABASE: rice_product
      MYSQL_USER: admin
      MYSQL_PASSWORD: rice
      TZ: Asia/Bangkok
    networks:
      ecp_req_network:
        ipv4_address: 192.168.129.4
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rice_phpmyadmin
    restart: unless-stopped
    ports:
      - "4903:80"
    environment:
      PMA_HOST: mariadb  # ใช้ mariadb แทน db
      MYSQL_ROOT_PASSWORD: adminppl
      PMA_LANGUAGE: th
      TZ: Asia/Bangkok
    depends_on:
      - mariadb  # เปลี่ยนจาก db เป็น mariadb
    networks:
      ecp_req_network:
        ipv4_address: 192.168.129.5

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install", "--no-interaction"]
    networks:
      ecp_req_network:
        ipv4_address: 192.168.129.6

networks:
  ecp_req_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.129.0/24

volumes:
  db_data:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
