openapi: 3.0.0
info:
  title: RiceProduct API
  version: 1.0.0
paths:
  /api/food_product:
    get:
      summary: Get all food_product
      responses:
        '200':
          description: A list of food_product