openapi: 3.0.0
info:
  title: RiceProduct API
  version: 1.0.0
  description: API สำหรับดึงข้อมูลผลิตภัณฑ์ข้าว โดยต้องมี access_token เพื่อเข้าถึง พบปัญหาสอบถาม นายปรัชญาพล จำปาลาด 0909691701
paths:
  /api/food_product:
    get:
      summary: Get all food_product
      security:
        - bearerAuth: []
      tags:
        - ข้อมูลผลิตภัณฑ์อาหาร table FoodProduct
      responses:
        '200':
          description: A list of food_product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FoodProduct'
        '401':
          description: Access token required
        '403':
          description: Invalid access token
        '500':
          description: Internal server error

/api/cosmetic_product:
    get:
      summary: Get all cosmetic_product
      security:
        - bearerAuth: []
      tags:
        - ข้อมูลผลิตภัณฑ์เครื่องสำอาง table cosmetic_Product
      responses:
        '200':
          description: A list of cosmetic_product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CosmeticProduct'
        '401':
          description: Access token required
        '403':
          description: Invalid access token
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FoodProduct:
      type: object
      properties:
        food_product_id:
          type: integer
        rice_id:
          type: integer
          nullable: true
        rice_variety_th_name:
          type: string
          nullable: true
        rice_variety_en_name:
          type: string
          nullable: true
        product_name:
          type: string
          nullable: true
        product_group:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        rice_variety_group_th_name:
          type: string
          nullable: true
        rice_variety_group_en_name:
          type: string
          nullable: true
        source_url:
          type: string
          nullable: true
        source:
          type: string
          nullable: true
        ingredients_and_equipment:
          type: string
          nullable: true
        instructions:
          type: string
          nullable: true
        ingredients_and_equipment_en:
          type: string
          nullable: true
        instructions_en:
          type: string
          nullable: true
        product_name_th:
          type: string
          nullable: true
        product_name_en:
          type: string
          nullable: true
        picture:
          type: string
          nullable: true

    CosmeticProduct:
      type: object
      properties:
        cosmetic_product_id:
          type: integer
        rice_id:
          type: integer
          nullable: true
        rice_variety_th_name:
          type: string
          nullable: true
        rice_variety_en_name:
          type: string
          nullable: true
        product_name:
          type: string
          nullable: true
        product_group:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        rice_variety_group_th_name:
          type: string
          nullable: true
        rice_variety_group_en_name:
          type: string
          nullable: true
        source_url:
          type: string
          nullable: true
        source:
          type: string
          nullable: true
        ingredients_and_equipment:
          type: string
          nullable: true
        instructions:
          type: string
          nullable: true
        ingredients_and_equipment_en:
          type: string
          nullable: true
        instructions_en:
          type: string
          nullable: true
        product_name_th:
          type: string
          nullable: true
        product_name_en:
          type: string
          nullable: true
        picture:
          type: string
          nullable: true